TaskManagement/Controllers/TaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TaskManagement.Data;
using TaskManagement.Models;
using TaskManagement.ViewModel;

namespace TaskManagement.Controllers
{
    public class TaskController : Controller
    {
        private readonly TaskMDbContext dbContext;

        public TaskController(TaskMDbContext dbContext)
        {
            this.dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        [HttpGet]
        public async Task<IActionResult> AddTask()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await dbContext.Users.FindAsync(userId);
            ViewBag.CurrentUser = user;

            if (user?.JobPosition != "مدير")
            {
                return Forbid();
            }

            var users = await dbContext.Users
                .Where(u => u.JobPosition == "موظف")
                .Select(u => new { u.Id, u.FullName, u.JobTitle })
                .ToListAsync();

            var viewModel = new AddTaskViewModel
            {
                AvailableRecipients = users
                    .Select(u => new SelectListItem
                    {
                        Value = u.Id,
                        Text = $"{u.JobTitle} - {u.FullName}"
                    })
                    .ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddTask(AddTaskViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var task = new Tasks
                {
                    Title = viewModel.Title,
                    Description = viewModel.Description,
                    Priority = viewModel.Priority,
                    Deadline = viewModel.Deadline,
                    RecipientId = viewModel.SelectedRecipientId,
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                };

                await dbContext.Tasks.AddAsync(task);
                await dbContext.SaveChangesAsync();

                TempData["SuccessMessage"] = "تم إرسال المهمة بنجاح!";
                return RedirectToAction("AddTask");
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> TaskReception()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await dbContext.Users.FindAsync(userId);
            ViewBag.CurrentUser = user;

            if (user?.JobPosition != "موظف")
            {
                return Forbid();
            }

            var tasks = await dbContext.Tasks
                .Include(t => t.User)
                .Where(t => t.RecipientId == userId &&
                            t.Status != "مرفوضة" &&
                            t.Status != "مقبولة")
                .Select(t => new TaskReceptionViewModel
                {
                    SenderFullName = $"{t.User.FullName} - {t.User.JobTitle}",
                    Title = t.Title,
                    Description = t.Description,
                    Priority = t.Priority,
                    Deadline = t.Deadline,
                    TaskId = t.TaskId
                })
                .ToListAsync();

            return View(tasks);
        }

        [HttpPost]
        public async Task<IActionResult> AcceptTask(int taskId)
        {
            var task = await dbContext.Tasks.FindAsync(taskId);
            if (task != null)
            {
                task.Status = "مقبولة";
                await dbContext.SaveChangesAsync();
            }
            return RedirectToAction("TaskReception");
        }

        [HttpPost]
        public async Task<IActionResult> RejectTask(int taskId)
        {
            var task = await dbContext.Tasks.FindAsync(taskId);
            if (task != null)
            {
                task.Status = "مرفوضة";
                await dbContext.SaveChangesAsync();
            }

            return RedirectToAction("TaskReception");
        }

        [HttpGet]
        public async Task<IActionResult> TrackTask()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await dbContext.Users.FindAsync(userId);
            ViewBag.CurrentUser = user;

            if (user == null || user.JobPosition != "موظف")
            {
                return Forbid();
            }

            var tasks = await dbContext.Tasks
                .Where(t => t.RecipientId == userId &&
                            t.Track != "منجزة" &&
                            t.Track != "متأخرة تم الإنجاز" &&
                            t.Track != "متأخرة لم يتم الإنجاز" &&
                            t.Track != "غير منجزة" &&
                            t.Status == "مقبولة")
                .Select(t => new TrackTaskViewModel
                {
                    TaskId = t.TaskId,
                    Title = t.Title,
                    Priority = t.Priority,
                    Deadline = t.Deadline,
                    Track = GetTaskStatus(t.Deadline, t.Track)
                })
                .ToListAsync();

            return View(tasks);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateTaskStatus(int taskId, string updatedStatus)
        {
            var task = await dbContext.Tasks.FindAsync(taskId);

            if (task != null)
            {
                var currentDate = DateTime.Now;

                if (updatedStatus == "منجزة")
                {
                    if (task.Deadline == null || task.Deadline >= currentDate)
                    {
                        task.Track = "منجزة";
                    }
                    else
                    {
                        task.Track = "متأخرة تم الإنجاز";
                    }
                }
                else if (updatedStatus == "غير منجزة")
                {
                    if (task.Deadline.HasValue && currentDate > task.Deadline)
                    {
                        task.Track = "متأخرة لم يتم الإنجاز";
                    }
                    else
                    {
                        task.Track = "غير منجزة";
                    }
                }

                await dbContext.SaveChangesAsync();
            }

            return RedirectToAction("TrackTask");
        }

        [HttpGet]
        public async Task<IActionResult> TaskList()
        {
            var userId = User.Identity.Name;
            var user = await dbContext.Users.FirstOrDefaultAsync(u => u.UserName == userId);
            ViewBag.CurrentUser = user;

            if (user == null || user.JobPosition != "مدير")
            {
                return Forbid();
            }

            var tasks = await dbContext.Tasks
                .Include(t => t.Recipient)
                .Where(t => t.UserId == user.Id)
                .Select(t => new TaskListViewModel
                {
                    TaskId = t.TaskId,
                    RecipientFullName = $"{t.Recipient.FullName} - {t.Recipient.JobTitle}",
                    Title = t.Title,
                    Priority = t.Priority,
                    Deadline = t.Deadline,
                    Status = GetTaskStatus(t.Deadline, t.Track)
                })
                .ToListAsync();

            return View(tasks);
        }

        public static string GetTaskStatus(DateTime? deadline, string currentStatus)
        {
            var currentDate = DateTime.Now;

            if (currentStatus == "منجزة")
            {
                return "منجزة";
            }

            if (currentStatus == "متأخرة تم الإنجاز")
            {
                return "متأخرة تم الإنجاز";
            }

            if (currentStatus == "غير منجزة")
            {
                return "غير منجزة";
            }

            if (deadline.HasValue && currentDate > deadline)
            {
                return "متأخرة لم يتم الإنجاز";
            }

            return "غير منجزة";
        }
    }
}

TaskManagement/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" />
</head>
<body>

    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagement/Views/Shared/_Layout.cshtml
@using System.Security.Claims


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestBotstrap</title>
    <script src="~/js/site.js"></script> <!-- ضع المسار الصحيح لملف JavaScript -->
    <link rel="stylesheet" href="~/css/Class.css" />



    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestBotstrap.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
  
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark" >
            <div class="container-fluid"> 
                @* style="background-color: green;" *@
                <a class="navbar-brand" href="#"> TM </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01" >
                    @* style="background-color: aqua;" *@
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">خدماتنا</a>
                            <div class="dropdown-menu ">
                                @* style="background-color: #f8f9fa; color: #333;" *@
                                    @{
                                        var user = ViewBag.CurrentUser; // استرجاع بيانات المستخدم من ViewBag
                                    }

                                    @if (user != null && user.JobPosition == "مدير") // تحقق مما إذا كان المستخدم مديرًا
                                    {
                                    <a class="dropdown-item" href="@Url.Action("AddTask", "Task")">إضافة مهمة</a>
                                    <a class="dropdown-item" href="@Url.Action("TaskList", "Task")">قائمة المهام</a> <!-- الرابط الذي يظهر فقط إذا كان المستخدم مديرًا -->
                                    }  
                                    @if (user != null && user.JobPosition == "موظف") // تحقق مما إذا كان المستخدم مديرًا
                                    {
                                    <a class="dropdown-item" href="@Url.Action("TaskReception", "Task")">استقبال المهام </a> <!-- الرابط الذي يظهر فقط إذا كان المستخدم مديرًا -->
                                    <a class="dropdown-item" href="@Url.Action("TrackTask", "Task")">متابعة المهام</a> <!-- الرابط الذي يظهر فقط إذا كان المستخدم مديرًا -->
                                    }



                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="javascript:void(0);" onclick="confirmLogout('@Url.Action("Logout", "Account")')">تسجيل خروج</a>
</div>
                        </li>
                    </ul>
                  
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestBotstrap - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
   


    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>